platform :ios, '11.0'
swift_version = "4.1"
use_frameworks!
inhibit_all_warnings!

target 'SciTube' do
  
  pod 'FLEX', '~> 2.4.0', :configurations => ['Debug']
  pod 'SwiftLint', '~> 0.29.1'
  pod 'Alamofire', '~> 4.8.0'
  pod 'AlamofireImage', '~> 3.5'
  pod 'RealmSwift', '~> 3.13.0'

end
